# Generated by Django 3.2.10 on 2022-01-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand name')),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Full price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discounted price')),
                ('discount_amount', models.IntegerField(blank=True, null=True, verbose_name='Discount in percentage')),
                ('component', models.CharField(choices=[('FR', 'Frame'), ('WS', 'Wheel Set'), ('DT', 'Drive Train'), ('HB', 'Handle Bar'), ('ST', 'Stem'), ('SP', 'Seat Post'), ('SA', 'Saddle'), ('BB', 'Bottom Bracket'), ('SI', 'Special Item')], default='FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottombracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottombracket', to='calculator.brand')),
                ('drivetrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivetrain', to='calculator.brand')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame', to='calculator.brand')),
                ('handlebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlebar', to='calculator.brand')),
                ('saddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saddle', to='calculator.brand')),
                ('seatpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatpost', to='calculator.brand')),
                ('special_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_items', to='calculator.brand')),
                ('stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stem', to='calculator.brand')),
                ('wheelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheelset', to='calculator.brand')),
            ],
        ),
    ]
