# Generated by Django 3.2.10 on 2022-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted price'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Full price'),
        ),
    ]
