# Generated by Django 3.2.10 on 2022-01-05 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20220104_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+50XXXXXXX'.", regex='^\\+?1?\\d{9,9}$')])),
                ('street_adress', models.CharField(max_length=200, verbose_name='Street Adress')),
                ('area', models.CharField(max_length=200, verbose_name='Area')),
                ('city', models.CharField(choices=[('AD', 'Abu Dhabi'), ('DB', 'Dubai'), ('SH', 'Sjarjah'), ('AJ', 'Ajman'), ('UQ', 'Umm Al Quwain'), ('RK', 'Ras Al Khaimah'), ('FU', 'Fujairah')], default='DB', max_length=2)),
            ],
        ),
    ]
